//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveMatch
    {
        public int Id { get; set; }
        public int MatchId { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    
        public virtual Match Match { get; set; }
    }
}
